### PR TITLE
Rename `fragment_directory` option to `fragment-directory`

### PR DESCRIPTION
**Pull request by jwodder**
For consistency with other options.

### CODE REVIEW

**Comment by yarikoptic** [comment]
And here will come `@v1` eventually ;) that option was already used in the 

```
❯ git grep fragment_directory
.datalad-release-action.yaml:fragment_directory: changelog.d
changelog.d/scriv.ini:fragment_directory = changelog.d
 ~datalad/datalad-container  master ▓▒░─
```

so may be time to try using `@v0` there?  but it seems we do not have that yet here:

```
❯ git tag
v0.0.0
v0.1.0
❯ git branch -a
  bf-template
  gh-14
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/fix
  remotes/origin/fragdir
  remotes/origin/gh-12
  remotes/origin/gh-14
  remotes/origin/gh-18
  remotes/origin/gh-22
  remotes/origin/gh-5
  remotes/origin/init
  remotes/origin/master
  remotes/origin/output-file
  remotes/origin/typing
```
? was I too quick to assume that a moving ref (branch?) for `vMAJOR` was implemented?

**Comment by jwodder** [comment]
@yarikoptic 

* `fragment*directory` defaults to `changelog.d` if not set, so unless some repo has already set it to a non-default value (which I don't believe any have), this won't cause any breakage.
* See #21 for the problem with the major version tag.

**Comment by yarikoptic** [comment]
> * `fragment*directory` defaults to `changelog.d` if not set, so unless some repo has already set it to a non-default value (which I don't believe any have), this won't cause any breakage.

ah, indeed. it just would be not used/misleading so better be stripped off anyways, right?

**Comment by yarikoptic** [comment]
since safe -- let's proceed!

**Pull request merged**
